name: Create and publish a package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Clone MFKN/oz-web
      uses: actions/checkout@v2
      with:
        repository: MFKN/oz-web
        token: ${{ secrets.API_TOKEN }}
        path: 'web'

    - name: test
      run: |
        cd ./web
        echo -e "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}\n@banou26:registry=https://npm.pkg.github.com" > .npmrc
        echo "$(<.npmrc)"
        npm ci --ignore-scripts
        cd ..

    - name: test
      run: |
        pwd
        ls

    - name: Clone banou26/oz-lib
      uses: actions/checkout@v2

    - name: Get dependencies for oz-lib
      run: |
        npm ci
        npm run build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.API_TOKEN }}

    - name: test
      run: |
        pwd
        ls
        cd oz-lib
        pwd
        ls
        cd dist
        pwd
        ls

    - name: Upload dist folder artifacts
      uses: actions/upload-artifact@v2
      with:
          name: dist
          path: "oz-lib/dist/*"

  package:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Download dist folder artifacts
        uses: actions/download-artifact@v2
        with:
            name: dist
            path: ./dist

      - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
      - run: npm pack

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: package
            path: "*.tgz"

  publish:
    name: "Publish to GitHub Packages"
    needs: [package]
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'Banou26'
    steps:
    - name: Download package artifact
      uses: actions/download-artifact@v2
      with:
          name: package
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
        registry-url: https://npm.pkg.github.com/
        scope: "@Banou26"
    - run: echo "registry=https://npm.pkg.github.com/@Banou26" >> .npmrc
    - run: npm publish $(ls *.tgz)
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
